### ISSUE TITLE
Won't let me sign in to anything

### ISSUE THREAD

**Issue by peeeepooop** [binary-person/womginx#1]
I don't know if it was on purpose or a bug, but when I try to sign in on any account using the proxy, it keeps saying the password is wrong. I really hope you can fix this bug because this proxy is extremely good

**Comment by binary-person** [comment]
can you list the sites that you can't sign in into? also, womginx doesn't support logins on most. Just discord is supported at the moment

**Comment by peeeepooop** [comment]
The sites that I can't sign into are Netflix, Hulu, and Outlook. Also thanks for letting me know that only Discord is supported for right now.

**Comment by binary-person** [comment]
I don't plan to support those websites currently, since the cookie header rewrites are near-impossible to get it to work with nginx
