### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by pecocksir** [binary-person/womginx#101]
500 Internal Server Error when I try to go to a website and refresh.

**Comment by binary-person** [comment]
can you paste the full url here

**Comment by pecocksir** [comment]
https://www.crazygames.com/game/big-flappy-tower-vs-tiny-square

**Comment by Strange-Oddball** [comment]
https://womginx.arph.org has finally been block by our school. @binary-person  Could you suggest a few other sites?

**Comment by binary-person** [comment]
the official instance does not throw that 500 error. if you can replicate this on the official demo, please reopen
