### ISSUE TITLE
white blank page in Discord on iOS safari

### ISSUE THREAD

**Issue by ThatOneKidAtSchool** [binary-person/womginx#104]
Purely doesn’t work returns a blank page when trying to sign in

**Comment by Degen-dev** [comment]
Are you on iOS? Asking because the only place where I have experienced this issue is on iOS.

**Comment by ThatOneKidAtSchool** [comment]
Yes only on iOS I’m using degeneracy so I’d didn’t report it to degeneracy issues

**Comment by binary-person** [comment]
this is kind of hard to debug. i'll find a way later in the weeks when i have time
