### ISSUE TITLE
website blocked

### ISSUE THREAD

**Issue by Barnac1ed** [binary-person/womginx#106]
my school blocks the website when i go to discord, is there a way to make the URL of the website you are trying to go to encoded in base 64?

ex: (current) https://womginx.binary-person.repl.co/main/https://www.google.com/ => (my idea) https://womginx.binary-person.repl.co/main/aHR0cHM6Ly9nb29nbGUuY29t
(and ik those aren't the right URLs btw)

thx in advance!

**Comment by es183923** [comment]
Duplicate of #43 

---
tldr, not possible
