### ISSUE TITLE
Captcha on Discord not working

### ISSUE THREAD

**Issue by sz6084** [binary-person/womginx#107]
The captcha on Discord is not working when I try to log in
![Screenshot 2022-03-10 6 02 27 PM](https://user-images.githubusercontent.com/101011086/157787864-0ba4929f-201a-4cc3-84ec-b6b52dc4e1cf.png)
.
Discord may be using another captcha service, like hCaptcha?

I also noted some lag

New to things here, so if I get something wrong let me know!

**Comment by IbossCloudDeathAccount** [comment]
I know, i hope they fix that. Its because it is a different captcha called hCaptcha.

**Comment by Vocal3D** [comment]
> The captcha on Discord is not working when I try to log in ![Screenshot 2022-03-10 6 02 27 PM](https://user-images.githubusercontent.com/101011086/157787864-0ba4929f-201a-4cc3-84ec-b6b52dc4e1cf.png) . Discord may be using another captcha service, like Captcha?
> 
> I also noted some lag
> 
> Impressive work by the way, since most other web proxies will not display Discord properly
> 
> New to things here, so if I get something wrong let me know!
> 
> Sam Z Email me at: [readerat9@gmail.com](mailto:readerat9@gmail.com)



> I know, i hope they fix that. Its because it is a different captcha called hCaptcha.

Use the qr code to sign in

**Comment by Vocal3D** [comment]
use qr code to sign in it bypasses 2fa and everything

**Comment by sz6084** [comment]
I don't have a phone...
