### ISSUE TITLE
heroku application error

### ISSUE THREAD

**Issue by IbossCloudDeathAccount** [binary-person/womginx#113]
The proxy is down for Heroku instances. It says application error and I can't access any of the sites I want to. Please fix this!
![Screenshot 2022-03-30 8 38 30 AM](https://user-images.githubusercontent.com/100983557/160836190-4dfc4d7d-1383-43a8-b87d-5efe7a4895cc.png)

**Comment by Charlie0998** [comment]
if u find the new one pls send it here

**Comment by Vocal3D** [comment]
> 

i have another 41 that are online just make your own so you dont have to worry about it

**Comment by Charlie0998** [comment]
can u give me the code > > 
> 
> 
> 
> i have another 41 that are online just make your own so you dont have to worry about it

**Comment by Vocal3D** [comment]
nah but you can make them for free https://awesomeopensource.com/project/binary-person/womginx
then press run / deploy on herku app or repl.it

**Comment by Vocal3D** [comment]
> The proxy is down for Heroku instances. It says application error and I can't access any of the sites I want to. Please fix this! ![Screenshot 2022-03-30 8 38 30 AM](https://user-images.githubusercontent.com/100983557/160836190-4dfc4d7d-1383-43a8-b87d-5efe7a4895cc.png)

also that is a public version of womginx meaning anyone could own it meaning your passwords could be compermised just make youur own

**Comment by binary-person** [comment]
show logs in heroku dashboard

**Comment by IbossCloudDeathAccount** [comment]
can someone give me one of theirs?

**Comment by binary-person** [comment]
please reopen when you have the chance to paste logs from the heroku console, as it's impossible for me to know why this is happening
