### ISSUE TITLE
customization features when cloning repos, and deployment methods 

### ISSUE THREAD

**Issue by zdc54** [binary-person/womginx#16]
How would I deploy another NGINX Proxy on a cloned repo to Heroku on Chrome OS? I have a cloned repo, and I am unable to open it or host it. Help would be greatly appreciated.

**Comment by binary-person** [comment]
where did you clone the repo to? if you forked or cloned it on github, you should be able to click the `Deploy to Heroku` button in the readme and it will deploy automatically

**Comment by zdc54** [comment]
I cloned the repo, and when I click Deploy To Heroku on the cloned repo, it loads forever.

**Comment by binary-person** [comment]
did you wait at least 10 minutes?

**Comment by zdc54** [comment]
yes, i left the tab running for at least 15 mins.

**Comment by binary-person** [comment]
can you take a screenshot?

**Comment by zdc54** [comment]
ok, brb for a while

**Comment by zdc54** [comment]
![Screenshot 2021-03-22 at 10 28 35 AM](https://user-images.githubusercontent.com/79989816/112015092-805cfe80-8af9-11eb-8beb-ffc699561b69.png)

**Comment by binary-person** [comment]
it just loads like this forever?

**Comment by zdc54** [comment]
ill be able to chat for 1 minute, then i gtg. ill get back to you.

**Comment by zdc54** [comment]
yup

**Comment by binary-person** [comment]
I can't help you. it's not an issue related to womginx nor something I can fix
