### ISSUE TITLE
zombs io not working(I provided a screenshot of chrome dev tools)

### ISSUE THREAD

**Issue by easella** [binary-person/womginx#17]
![image](https://user-images.githubusercontent.com/74786054/111838364-9dae8480-88cf-11eb-98c4-05f3914abc0a.png)

**Comment by binary-person** [comment]
looks like this issue applies to all womginx instances deployed by heroku. zombs.io likely banned the IP of heroku machines. In the meantime, you can try the demo link in the readme

**Comment by easella** [comment]
it does not work. With the demo whenever you try to go to an http site this pops up.
![image](https://user-images.githubusercontent.com/74786054/111886803-f3099500-89a6-11eb-99fc-1884309443ca.png)

**Comment by binary-person** [comment]
click details => proceed

**Comment by easella** [comment]
there is nothing that says "proceed"
![image](https://user-images.githubusercontent.com/74786054/111887055-e2f2b500-89a8-11eb-8bcd-c15a94611b3f.png)

**Comment by binary-person** [comment]
type `thisisunsafe`

**Comment by easella** [comment]
what do you mean?

**Comment by binary-person** [comment]
on that page, type `thisisunsafe` literally

**Comment by binary-person** [comment]
don't mindlessly type this though. there's a reason why chrome doesn't want you to proceed

**Comment by easella** [comment]
does not work

**Comment by easella** [comment]
I typed the word "unsafe" and it did nothing/

**Comment by binary-person** [comment]
type `thisisunsafe`

**Comment by easella** [comment]
I did and it worked

**Comment by easella** [comment]
zombs io works. thank you.

**Comment by easella** [comment]
it says 403 forbidden.
![Uploading image.png…]()

**Comment by easella** [comment]
can you deploy this to codesandbox or glitch.me?
