### ISSUE TITLE
does not work through iframes

### ISSUE THREAD

**Issue by easella** [binary-person/womginx#18]
when i embed this in an iframe it does not work. How do I fix this?
![image](https://user-images.githubusercontent.com/74786054/111888264-5c8ea100-89b1-11eb-9d68-aca8a1a62293.png)

**Comment by binary-person** [comment]
it's a security feature of womginx currently. you'll have to go to the main proxy page first for it to set the session cookie

**Comment by easella** [comment]
can you fix it? And can you deploy cnn proxy to heroku? Can you also make more proxies? My school blocks everything. If you make a new proxy make sure you add a deploy to heroku button and that it works with zombs io and http/https.

**Comment by binary-person** [comment]
no. do not open any more issues

**Comment by binary-person** [comment]
no. we're done here. do not open any more issues

**Comment by BinBashBanana** [comment]
I wish I could be that blunt. this person opens issues EVERYWHERE. (Like, even on node unblocker.)
