### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Spritzerland** [binary-person/womginx#2]
Does using discord with womginx get you banned from discord?

**Comment by binary-person** [comment]
no. but multiple users using discord under the same ip will flag all of them using it under the same ip on the suspicion that they are bot accounts. as long as you have a verification method (phone), you're fine

**Comment by Spritzerland** [comment]
Does it hide your actual IP?

**Comment by binary-person** [comment]
yes, but i would not guarantee as wombat still has some things that don't get proxied
