### ISSUE TITLE
discord support not working

### ISSUE THREAD

**Issue by zdc54** [binary-person/womginx#20]
When I try to login to discord it says ¨form field required", even though I already typed it. And when I try to verify, it gets stuck on ¨Authenicating...¨. Is there a way to fix this?

**Comment by binary-person** [comment]
i tried it. it works for me. can you post a screenshot

**Comment by zdc54** [comment]
![Screenshot 2021-04-09 10 37 52 AM](https://user-images.githubusercontent.com/79989816/114205242-b5ea5000-991f-11eb-9651-eec1ea26bbc5.png)

**Comment by binary-person** [comment]
Open chrome dev tools and under chrome dev tools, take a screenshot

**Comment by zdc54** [comment]
I'll try.

**Comment by zdc54** [comment]
I can't use devtools on my device.

**Comment by zdc54** [comment]
Are there any features you need to know? I have an inspect element bookmarklet, but it isn't working.

**Comment by zdc54** [comment]
Never mind, I got it! I just had to change the app name on Heroku. Thanks!

**Comment by dhruviyengar** [comment]
This happens to me too, and I restarted my service. Perhaps consider reopening it? It's getting a 400 response from the Discord API
![image](https://user-images.githubusercontent.com/75268452/158102664-a9279b4a-f460-4f97-b092-00c597fe0312.png)

**Comment by nevr13** [comment]
this issue is literally over a year old

**Comment by dhruviyengar** [comment]
lol im trying to get it reopened, not all of us host on heroku.
