### ISSUE TITLE
Discord support isn't working, even with the QR code. Loads indefinitely.

### ISSUE THREAD

**Issue by zdc54** [binary-person/womginx#25]
CLASS 3: BRUH MOMENT

Ok, I hopped on discord today, and I logged in with my QR Code. It worked, but it didn't log in. Is there a reason for this? Thanks in advance.

**Comment by binary-person** [comment]
clear browser cookies and retry

**Comment by zdc54** [comment]
I need to delete and remake it, maybe there are too many people using my heroku link. not good. thanks!
