### ISSUE TITLE
aaaaaaa

### ISSUE THREAD

**Issue by rr2826** [binary-person/womginx#29]
![image](https://user-images.githubusercontent.com/71412967/117988608-6ddc9580-b2f0-11eb-82ee-c72bb2492046.png)

- [ ] 
![image](https://user-images.githubusercontent.com/71412967/117988641-76cd6700-b2f0-11eb-9976-9d987124d42f.png)
fix pez i need it to play games

**Comment by binary-person** [comment]
you have two options:

1. host your own or use deploy to heroku button
2. use an alternative
