### ISSUE TITLE
Proxied pages are messed up on extra domains

### ISSUE THREAD

**Issue by MichaelBest01** [binary-person/womginx#3]
I made https://womgnix.herokuapp.com/ and everything works fine on it, but when I used a side domain like https://wgx.studentontask.cf the page starts not to load correctly. These are both from the same Heroku just one has a custom domain when the other doesn't.

**Comment by binary-person** [comment]
Can you show a link that doesn't work? Google works for me

**Comment by MichaelBest01** [comment]
https://wgx.studentontask.cf/main/https://discord.com/login everything is loaded incorrectly

**Comment by binary-person** [comment]
are you using using cloudflare + heroku? cloudflare sends an http request to your heroku instance, which is causing womginx to think it's a http, so it rewrites everything under http://, making chrome block the insecure request. try enabling https for your connection from cloudflare to heroku

**Comment by BinBashBanana** [comment]
(I have been wondering the same exact thing, with pywb though, it has the same problem)

Under the TLS section on cloudflare, only flexible and none options work, meaning that traffic is always http between cloudflare and the heroku server. I remember reading somewhere that heroku does not support extra HTTPS certificates for custom domains, so maybe there would be a workaround for this?

**Comment by MichaelBest01** [comment]
> are you using using cloudflare + heroku? cloudflare sends an http request to your heroku instance, which is causing womginx to think it's a http, so it rewrites everything under http://, making chrome block the insecure request. try enabling https for your connection from cloudflare to heroku

I went to it and it is set to flexible on the TLS. If I turn it off it will turn off https which I need and when setting it to Full gives a 525 error.

**Comment by binary-person** [comment]
https://github.com/binary-person/womginx/blob/c0891122cc7cdd502920238daf50ac455c9d0ae0/nginx.conf#L34

to force https, change from
```
    map $http_x_forwarded_proto $relativescheme {
        default $http_x_forwarded_proto;
        '' $scheme;
    }
```
to
```
    map $http_x_forwarded_proto $relativescheme {
        default 'https';
    }
```

**Comment by BinBashBanana** [comment]
Wow, it worked thanks!
What exactly does this modification do, like always return a https protocol no matter what? Or something else?

**Comment by binary-person** [comment]
it forces nginx to always rewrite with https
