### ISSUE TITLE
Embeds on Google Sites Getting Error 403

### ISSUE THREAD

**Issue by Woofydude** [binary-person/womginx#31]
I'm using this on Heroku and whenever I try to embed discord on google sites, I get 403 error. I'm pretty sure I know why it is happening (blacklist of user agents in the config file) but I cannot edit that on Heroku to change it. Any solutions or help?

**Comment by binary-person** [comment]
does it say "sorry, you're not allowed to access this content"? that would appear if it's blocking by user agent.

the cookies need to be set. see #9 .

Reopen if you're still experiencing issues

**Comment by Woofydude** [comment]
It just says 403 Forbidden nginx/1.14.0 (Ubuntu). I do not think the cookies need to be set. For more details into this issue, what I am doing is pasting the URL to the discord login page as an embed on google sites. The URL will work normally but the proxy blocks it on a google site.

**Comment by Woofydude** [comment]
Also, I do not know how to reopen an issue. From what I read, it is impossible to reopen your own issue if you did not close it yourself.

**Comment by binary-person** [comment]
> I do not think the cookies need to be set

they do.

> It just says 403 Forbidden nginx/1.14.0 (Ubuntu).

that means cookies need to be set. only if it says "sorry, you're not allowed to access this content" does it mean you're blocked by user agent
