### ISSUE TITLE
discord indefinite loading after log in

### ISSUE THREAD

**Issue by clumsykiller** [binary-person/womginx#35]
also tried reloading multiple times

**Comment by binary-person** [comment]
this is a discord issue, not a womginx issue. you can try the official discord website and it will exhibit the same behavior.

**Comment by clumsykiller** [comment]
alright thank you

**Comment by Kore-Development** [comment]
Is this an issue that would ever be fixed?

**Comment by Kore-Development** [comment]
the qr code also never loads

**Comment by clumsykiller** [comment]
he doesnt know ask discord
