### ISSUE TITLE
question and problem!!

### ISSUE THREAD

**Issue by survey-corps-system** [binary-person/womginx#37]
hey! i've been trying to use discord on womginx, and unfortunately it won't let me log in, because i have to verify by email, and i can't verify because i can't access that email on my school computer. i've tried to use womginx for mail.google.com, although it never loads. it might be because i'm using womginx through holy unblocker. have you run into this before?

**Comment by binary-person** [comment]
i dont know what is it with discord issues, since it works for me. also, gmail is not supported
