### ISSUE TITLE
<title> Tag Not Working

### ISSUE THREAD

**Issue by ytJsuther** [binary-person/womginx#42]
Hi, I'm trying to make a thing where when a site is loaded it doesn't say the site's title so that it won't show on search history. I tried to change the <title> tag on index.html so it doesn't show NGINX **Proxy** since the word Proxy is blocked at my school but when I load up the site after changing and deploying to Heroku it still says NGINX Proxy at the top.

Can you please help me?

**Comment by binary-person** [comment]
sorry. I don't plan on changing the title. you're going to need to fork this repo instead and then modify the title to your liking

**Comment by binary-person** [comment]
can you deploy the heroku app from your repo and check to see if the title still doesn't change

**Comment by ytJsuther** [comment]
I’ve tried even downloading the repository to my computer and opening it in
google chrome as a file:///<location>

**Comment by binary-person** [comment]
you need to deploy your own site. can you provide a link of your repo and the deployed womginx instance

**Comment by ytJsuther** [comment]
HTTPS://jsuthdevub.herokuapp.com

**Comment by binary-person** [comment]
can you provide the repo to the deployed heroku instance

**Comment by ytJsuther** [comment]
https://GitHub.com/ytJsuther/womginx

**Comment by binary-person** [comment]
you need to click the deploy button on your own repository for changes from your repository to work

**Comment by binary-person** [comment]
I forgot. you also need to change this line in the dockerfile

https://github.com/ytJsuther/womginx/blob/1bd28b309a123b47e5ae158ab0e621d1e853a600/Dockerfile#L10

**Comment by ytJsuther** [comment]
> I forgot. you also need to change this line in the dockerfile
> 
> https://github.com/ytJsuther/womginx/blob/1bd28b309a123b47e5ae158ab0e621d1e853a600/Dockerfile#L10

I got it now thanks
