### ISSUE TITLE
hash the url

### ISSUE THREAD

**Issue by es183923** [binary-person/womginx#43]
Is it possible to hash or somehow obfuscate the website url?
eg:
from `https://womginx.example/main/https://www.google.com/` into `https://womginx.example/main/d0e196a0c25d35dd0a84593cbae0f38333aa58529936444ea26453eab28dfc86` (using sha256 hash)

**Comment by binary-person** [comment]
nginx cannot hash any urls. also, it would break too many things with rewriting. (also, you cannot reverse a hash. that's not what a hash is)

**Comment by es183923** [comment]
If hashes won't work, would it be possible to encode the URL? eg with base64 (or multiple times)? This makes it harder to easily tell what website is being visited.

**Comment by binary-person** [comment]
as i mentioned above, encoding urls will break rewriting. and also, nginx cannot encode any urls using any methods like base64
