### ISSUE TITLE
hCaptcha broken

### ISSUE THREAD

**Issue by MayMay39** [binary-person/womginx#44]
hCaptcha is broken across multiple proxies using Womginx including Holy Unblocker preventing access to Discord login the normal way

**Comment by clumsykiller** [comment]
yes it is please fix

**Comment by zdc54** [comment]
same lol

**Comment by foxsouns** [comment]
i was just using it yesterday: i think hcaptcha got an upgrade. :<

**Comment by clumsykiller** [comment]
i didnt see anything about an update when i went to the website

**Comment by foxsouns** [comment]
for reference, it's "space" on the site is reserved, but the captcha never loads. im going to check if this happens on corrosion so i can make sure it's not a womginx only problem

**Comment by clumsykiller** [comment]
any results?

**Comment by foxsouns** [comment]
working on it, my mirrors are being slow

**Comment by clumsykiller** [comment]
yeah its not working i just tried it

**Comment by clumsykiller** [comment]
kinda weird usually simon would have replied by now

**Comment by foxsouns** [comment]
pydodge gets closest to running hcaptcha, but doesnt get past the initial click.

**Comment by clumsykiller** [comment]
what is pydodge? ive never heard of it.

**Comment by rr2826** [comment]
same

**Comment by foxsouns** [comment]
[pydodge](https://github.com/BinBashBanana/PyDodge)
it's another proxy, used on [holyub](https://github.com/titaniumnetwork-dev/Holy-Unblocker)

**Comment by zdc54** [comment]
we know

**Comment by zdc54** [comment]
just leave this alone, and let him solve it. give them time.

**Comment by clumsykiller** [comment]
> [pydodge](https://github.com/BinBashBanana/PyDodge) it's another proxy, used on [holyub](https://github.com/titaniumnetwork-dev/Holy-Unblocker)

thank you

**Comment by rr2826** [comment]
i know that but what is the problem?

**Comment by MayMay39** [comment]
I'm seeing issues close left and right so I'm assuming Binary will get to this soon :)

**Comment by rr2826** [comment]
wow:(

**Comment by MayMay39** [comment]
Binary hasn't closed this issue so I'm assuming he's fixing it, thank you

**Comment by binary-person** [comment]
ok i found the problem. hcaptcha indeed changed their code. instead of adding a `Content Security Policy` in the header, they added it to a meta tag instead. going to fix it now

**Comment by clumsykiller** [comment]
ok thank you

**Comment by clumsykiller** [comment]
and i knew it was he/him or it would have been non binary person and also you have dude in your description

**Comment by MayMay39** [comment]
Woooo Binary saves the day once again!

**Comment by rr2826** [comment]
yes indeed thank you!

**Comment by rr2826** [comment]
yeeeeep

**Comment by clumsykiller** [comment]
its not fixed though yet right

**Comment by MayMay39** [comment]
Nah, he'll probably close the issue once fixed

**Comment by clumsykiller** [comment]
ok thanks

**Comment by MayMay39** [comment]
Just tried logging in and yeah he hasn't fixed said issue yet

**Comment by clumsykiller** [comment]
people are so smart i could never sit down and take the time to code adhd haunting me

**Comment by rr2826** [comment]
i think?

**Comment by rr2826** [comment]
and i have it :( and i fil you

**Comment by MayMay39** [comment]
Oh yeah btw I contacted QuiteAFancyEmerald on this same issue after Binary's reply so don't worry about Corrosion it'll get updated too :D

**Comment by clumsykiller** [comment]
i think i also made an issue on the git rep as well

**Comment by MayMay39** [comment]
Yeah I saw

**Comment by binary-person** [comment]
fixed with bd70ced. check the demo link to verify that the fix works

**Comment by clumsykiller** [comment]
ok thank you
