### ISSUE TITLE
hcaptcha broken not letting me log into discord

### ISSUE THREAD

**Issue by clumsykiller** [binary-person/womginx#46]

**Comment by clumsykiller** [comment]
@binary-person

**Comment by clumsykiller** [comment]
and how fast would you be able to fix it?

**Comment by zdc54** [comment]
same

**Comment by clumsykiller** [comment]
i just hope he can fix it fast

**Comment by zdc54** [comment]
coding takes time, and also binary-person uses they/them.

**Comment by clumsykiller** [comment]
oh im sorry i didnt know and ok

**Comment by clumsykiller** [comment]
i figured they were he/him because their profile description uses the word dude

**Comment by zdc54** [comment]
it says binary in his name bruh

**Comment by zdc54** [comment]
*realization*

**Comment by MayMay39** [comment]
Yeah, I have the same problem, hCaptcha broke about 9PM EST last night and I think binary-person might've been bugfixing and accidentally broke it - or hCaptcha itself broke, I tried logging on on Discord with Corrosion

**Comment by binary-person** [comment]
> coding takes time, and also binary-person uses they/them.

thanks for the consideration, but it's "he/him." binary just refers to 0101 binary.

anyway, this is a duplicate of #44
