### ISSUE TITLE
safari

### ISSUE THREAD

**Issue by Atlas-Can-Code** [binary-person/womginx#47]
Why does the demo link only work sometimes and then other times I get a 403 forbidden

**Comment by zdc54** [comment]
it is what it is

**Comment by binary-person** [comment]
im going to fix it later. regardless, this is a duplicate of #9, so I'll be closing this issue

**Comment by tomhatesnerds** [comment]
403 error still happeninggg

**Comment by zdc54** [comment]
Aren't you on Christmas break or something? You prob don't need a proxy right now lol. Go ahead and type a forward slash (like this "/" but without the quotation marks), it should look like, "https://sitename.herokuapp.com/".
