### ISSUE TITLE
says unable to load user banner about me and has a yellow exclamation mark and doesnt show any of those

### ISSUE THREAD

**Issue by clumsykiller** [binary-person/womginx#49]

**Comment by clumsykiller** [comment]
on discord

**Comment by clumsykiller** [comment]
i think its because its not showing mutual servers but its showing mutual friends

**Comment by binary-person** [comment]
deploy your own proxy. it's because discord rate limits per ip, which means too many people are using discord under one single proxy

**Comment by clumsykiller** [comment]
i did but i guess i have to remake another one then thanks

**Comment by clumsykiller** [comment]
its still not working what can i do?

**Comment by binary-person** [comment]
sorry. cannot help you. it is a discord related issue, not womginx
