### ISSUE TITLE
I have deployed it to Heroku, how do I edit it? (Newbie question, not a bug report)

### ISSUE THREAD

**Issue by Dumbledore-web** [binary-person/womginx#50]
![image](https://user-images.githubusercontent.com/70784752/143193937-1644251c-5cf0-4e92-ad29-aeedcf678a6a.png)
I want to remove the branding on the home page and add the NSFW cloud flare filter... When I click deploy app (after I have linked it to Github) it doesn't do a thing.

**Comment by rr2826** [comment]
how do you deployed it to heroku?

**Comment by binary-person** [comment]
change https://github.com/binary-person/womginx/blob/b3763e55526ab7b5b8874e0dd009cbd4b0c60d33/Dockerfile#L10 to your own github repo

**Comment by binary-person** [comment]
an update to this. you no longer need to change it directly in the dockerfile as it now copies it from the current directory, which should be your latest changes
