### ISSUE TITLE
Keep Getting errors when building at 5/6 steps 

### ISSUE THREAD

**Issue by illusions-creator** [binary-person/womginx#54]
So i just changed the clone repo in the docker file so that it saves my css changes but now it gives me errors every time i build it.

![Capture](https://user-images.githubusercontent.com/73310622/143998370-f849ded7-8c5e-4bd0-bcbc-74e6f7db3e29.PNG)

**Comment by binary-person** [comment]
first off, do not open three new issues on the same topic. second, you did not clone this repository correctly. you are missing the wombat folder. your easiest option is to fork this repo and then make your changes to the dockerfile first, then your css

**Comment by binary-person** [comment]
sorry, those three weren't on the same topic. However, to avoid something like this, please give yourself at least 30 minutes to figure out what went wrong before posting an issue
