### ISSUE TITLE
Are there any other services you can run this proxy on?

### ISSUE THREAD

**Issue by Dumbledore-web** [binary-person/womginx#55]
RIP proxy it got blocked..

**Comment by binary-person** [comment]
not that i know of at the moment

**Comment by Burraby** [comment]
@binary-person Sorry for the mention but can you please delete this issue (I know it's already closed) thanks.

**Comment by binary-person** [comment]
There's no reason to

**Comment by Burraby** [comment]
> There's no reason to

Well you see.. this issue is now stuck on my profile and I don't really want to be linked to this project.

**Comment by binary-person** [comment]
alright then
