### ISSUE TITLE
discord not working

### ISSUE THREAD

**Issue by froggiiiit** [binary-person/womginx#57]
it says "This site can’t be reached The webpage at https://womginx.arph.org/main/discord.com might be temporarily down or it may have moved permanently to a new web address"

**Comment by dkbgskjdavnknjns** [comment]
yeah discord isnt working for me either

**Comment by meow6969** [comment]
im kms i need the discord on my chrome book

**Comment by binary-person** [comment]
it's working for me. post a screenshot if it's still not working

**Comment by froggiiiit** [comment]
![image](https://user-images.githubusercontent.com/95630950/144944184-c76e4bb3-d4a6-4df4-8bd7-6c4d98ffb4bb.png)

**Comment by binary-person** [comment]
That’s an issue with your proxy settings, which are either set by a chrome extension or enforced by your school

**Comment by froggiiiit** [comment]
aw :(

**Comment by DaCuteRaccoon** [comment]
![image](https://user-images.githubusercontent.com/72467156/170802811-5218a358-007a-4c50-aee7-6659947964f9.png)

**Comment by ibmoth** [comment]
> it says "This site can’t be reached The webpage at https://womginx.arph.org/main/discord.com might be temporarily down or it may have moved permanently to a new web address"

Hey, this thread is closed and pretty old but try using one of discord's other proxy sites. Either https://canary.discord.com or https://ptb.discord.com
