### ISSUE TITLE
cache problems.

### ISSUE THREAD

**Issue by TheFinality** [binary-person/womginx#58]
I'm making some edits to wombat handler.js, but it keeps caching. I want to make nginx.conf attach /wombat_handler.js?time=Date.now(), so how would i do Date.now() in the .conf file?

**Comment by binary-person** [comment]
it shouldn't cache if you do ctrl + shift + r. also, you can disable caching in chrome dev tools under the network tab by hitting the check mark "disable cache"

**Comment by TheFinality** [comment]
Yes, but I'm sharing this with friends, and I just wanna make it easier for them, so how can I make it like that?

**Comment by binary-person** [comment]
replace
https://github.com/binary-person/womginx/blob/b3763e55526ab7b5b8874e0dd009cbd4b0c60d33/nginx.conf#L302
with
```
    <script $processed_flag_attribute src="/wombat-handler.js?rand=$date_gmt" processed-attribute="$processed_flag_attribute">
```

**Comment by TheFinality** [comment]
Thanks!

**Comment by TheFinality** [comment]
When I do this, it returns 404. How can I fix this?

**Comment by binary-person** [comment]
add
```
        location ~^/wombat-handler.js*$ {
            alias /your/path/to/wombat-handler.js;
        }
```
before
https://github.com/binary-person/womginx/blob/b3763e55526ab7b5b8874e0dd009cbd4b0c60d33/nginx.conf#L126

**Comment by TheFinality** [comment]
can you tell me what to put exactly for your path to wombat handler? It gives 404 if i do /wombat-handler.js or /public/wombat-handler.js.

**Comment by binary-person** [comment]
`/your/path/to/wombat-handler.js;` for me would be `/home/binary/womginx/public/wombat-handler.js;`
hopefully that makes sense
