### ISSUE TITLE
Any way I can fix the roblox login?

### ISSUE THREAD

**Issue by pecocksir** [binary-person/womginx#61]
The roblox login is broken, any way I an fix it?

**Comment by illusions-creator** [comment]
what is broken about it ?

**Comment by binary-person** [comment]
please post screenshot with chrome dev tools's console tab open

**Comment by pecocksir** [comment]
my school has it blocked :( rip
(correct me if i am wrong, but dev tools is inspect element?)

**Comment by binary-person** [comment]
Yes

**Comment by pecocksir** [comment]
so i am screwed?

**Comment by binary-person** [comment]
i dont plan on supporting any more sites that don't work when this project got published
