### ISSUE TITLE
when i try to deploy to heroku it says the source code violates some kind of rule help

### ISSUE THREAD

**Issue by clumsykiller** [binary-person/womginx#62]

**Comment by SAVAGENOCHILL06** [comment]
I've been having the same issues also, I would like it if someone could troubleshoot or explain why this is happening if at all possible please.

**Comment by binary-person** [comment]
can you try forking it and see if it works

**Comment by binary-person** [comment]
also, this is something i cannot control. sorry

**Comment by binary-person** [comment]
i might make a change to the readme indicating that though
