### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by hi-my-name** [binary-person/womginx#64]
It says application error when i try to search something up (after i press go)

**Comment by binary-person** [comment]
screenshot logs please

**Comment by hi-my-name** [comment]
![Screenshot 2021-12-20 5 35 53 PM](https://user-images.githubusercontent.com/96305260/146855866-d3255dc5-46d9-4962-ba2f-6b518facb463.png)

**Comment by binary-person** [comment]
lookup how to view heroku logs, then paste the contents of the log to here

**Comment by hi-my-name** [comment]
The problem is that heroku.com is blocked on my computer

**Comment by hi-my-name** [comment]
it was working 4 days ago but then it just stopped working

**Comment by hi-my-name** [comment]
if i can't get access to heroku, then is there any other proxy site like this that i can use. Thanks!

**Comment by binary-person** [comment]
sorry. cant help you
