### ISSUE TITLE
503 Service Temporarily Unavailable on official demo

### ISSUE THREAD

**Issue by AggravatedToadd** [binary-person/womginx#66]
The official demo page says "503 Service Temporarily Unavailable" and works for like 30 seconds at a time right now. Is this an issue with too many people using the demo page right now, or is it something on my end?

**Comment by binary-person** [comment]
can you provide the url that causes the error? google.com works for me

**Comment by nyoosh** [comment]
I've been trying to use Discord with the demo proxy, but it gives said error. The website is working, but lots of elements in the page aren't displaying properly. For instance, images won't load and the regular font is set to default.

**Comment by binary-person** [comment]
does it still work now? you might have coincidentally been on the minute i was rebooting the vps

**Comment by es183923** [comment]
> The website is working, but lots of elements in the page aren't displaying properly. For instance, images won't load and the regular font is set to default.

This has happened to me on my self-hosted version. Reloading the page seems to fix the issue. It could be related to the request limits.

**Comment by binary-person** [comment]
i see. it's definitely related to rate limits, something i cannot control

**Comment by binary-person** [comment]
for anyone dropping by this issue, please reply "same here" to give me an idea of how many people are experiencing this error

**Comment by binary-person** [comment]
hold on, never mind. it's because docker nginx sees the same ip from all of you people requesting, so it's treating everyone under one rate limiter

**Comment by binary-person** [comment]
thanks for notifying me about this issue :+1:
