### ISSUE TITLE
Client stuck on connecting

### ISSUE THREAD

**Issue by nyoosh** [binary-person/womginx#69]
Alright, so the "Service Temporarily Unavailable" was fixed, but Discord still won't work. It's stuck on that one loading screen where it gives that "Did You Know?" stuff, and it shows "Connection Problems? Let us know!" at the bottom no matter how much I refresh. 
![Screenshot 2022-01-04 7 35 21 AM](https://user-images.githubusercontent.com/68951404/148066974-e3aad8b4-28fc-4813-9eca-299bb52ace4a.png)

**Comment by binary-person** [comment]
Can you post the console logs here? (It's in chrome dev tools under the Console tab)

**Comment by nyoosh** [comment]
And then below this, it just shows the regular "Hold Up!" warning about pasting stuff generated by Discord.
![Screenshot 2022-01-04 8 51 05 AM](https://user-images.githubusercontent.com/68951404/148077265-3327e268-6559-42c8-9bbf-b2b419d81528.png)

**Comment by binary-person** [comment]
can you refresh with chrome dev tools open

**Comment by binary-person** [comment]
if there's still no errors, go to network tab, wait 30 seconds, then if it doesn't load, screenshot that

**Comment by nyoosh** [comment]
![Screenshot 2022-01-04 2 30 18 PM](https://user-images.githubusercontent.com/68951404/148120085-3141109e-d121-42af-9f36-30a3bdd88fb7.png)
![Screenshot 2022-01-04 2 30 28 PM](https://user-images.githubusercontent.com/68951404/148120089-a9a6065d-82da-429c-a65f-c2c9d0a3cffb.png)

**Comment by binary-person** [comment]
it looks like the latest version of wombat breaks websocket, which is needed for discord. I'll lock the wombat version for now
