### ISSUE TITLE
[BUG] discord

### ISSUE THREAD

**Issue by irhrhd** [binary-person/womginx#7]
I cant use discord it wont let me create an account i try clicking and it doesnt work

**Comment by binary-person** [comment]
can you open dev tools, click the console tab, and take a screenshot of it?

**Comment by irhrhd** [comment]
No im on ipad i can screen shot the create account thing

**Comment by binary-person** [comment]
no, it's fine. I'll look into it when I have the time

**Comment by irhrhd** [comment]
Okay thank you

**Comment by irhrhd** [comment]
Have you looked at it yet

**Comment by binary-person** [comment]
it works. it's just that discord gets suspicious from the IP you're creating your account, forcing you to verify by phone.
reopen if there is an issue that very clearly breaks discord, instead of just "it doesn't work"
