### ISSUE TITLE
new redirecting doesn't work

### ISSUE THREAD

**Issue by es183923** [binary-person/womginx#75]
Instead of redirecting me, it sends me to a page with the following:
```
<script>location.href="/womginxaddcookie/"+Date.now()+"/"location.href</script>
```

**Comment by binary-person** [comment]
does it work in the demo?

**Comment by es183923** [comment]
Yes, but my version, with the exact same Dockerfile and nginx.conf does not.

**Comment by binary-person** [comment]
are you trying the docker setup I highlighted? and can you screenshot your chrome dev tools network tab after you clicked on the first entry after refresh

**Comment by es183923** [comment]
No, I'm not using docker-compose, as mentioned in the setup. I'm using the Dockerfile and docker directly. Could this be why? If so, is there any way to get the same results without docker-compose?

**Comment by binary-person** [comment]
it shouldn't matter. regardless, please screenshot chrome dev tools network after you clicked on the first entry after refresh

**Comment by es183923** [comment]
It seems to be related to me using a WebKit based browser instead of a Chromium based browser. It works perfectly fine on Chrome, but not on Safari. 

In Safari, the console is completely empty when I directly try to visit `https://myproxy.tld/main/https://www.google.com`

Here's an image:
![Screen Shot 2022-01-10 at 8 38 56 PM](https://user-images.githubusercontent.com/72744903/148866323-1b5e3db4-d681-45d4-acf0-086119c129a6.png)

**Comment by binary-person** [comment]
thats weird. can you try using the demo link? i tried it with my iphone safari and it works

**Comment by es183923** [comment]
The demo works perfectly fine though.

**Comment by es183923** [comment]
I just set a permanent cookie instead.

**Comment by binary-person** [comment]
it might be an issue related to your installation. note that you'll need https. reopen this issue if you need to
