### ISSUE TITLE
Google CloudShell

### ISSUE THREAD

**Issue by WmeLuna** [binary-person/womginx#79]
if you try to use this on cloudshell, many urls redirect to localhost.
ive noticed it only does this when the protocal isnt provided
example:
```https://##########.cloudshell.dev/main/discord.com```
redirects to 
```http://127.0.0.1/main/http://discord.com```

**Comment by binary-person** [comment]
that `127.0.0.1` came from
https://github.com/binary-person/womginx/blob/1e3de976f77fa0fdc9ef2aec1100410a2173276b/nginx.conf#L60
or more specifically, the `Host` header. google cloud shell's reverse proxy likely didnt forward the correct Host header, but instead, kept with 127.0.0.1. Not sure how to fix this, as i dont use cloud shell. either way, it's an issue that's not related to womginx, so i'll be closing this now, though if you do find the solution, please post it for others to see
