### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by programmeruser2** [binary-person/womginx#81]
I've been trying to setup this proxy, and a major issue I've run into is authentication. I don't want my instance to be open, so I've tried using HTTP authentication, however the Authorization header causes issues for applications that already use it. I believe there might be a way for a session cookie and web form type of authentication to be embedded into Nginx, however I'm not sure how I would implement it (ngx_http_auth_request_module?). What are the possible options that I could try?

**Comment by binary-person** [comment]
An idea is that you can have a hidden endpoint that sets the cookie, and remove the set-cookie header from everywhere else. That way, only users who know the hidden endpoint would be able to access it.

**Comment by binary-person** [comment]
I'm closing this as this isn't an issue, but continue to comment if needed.

**Comment by programmeruser2** [comment]
Thanks, I'll try that.
