### ISSUE TITLE
heroku deployment

### ISSUE THREAD

**Issue by Aesthetical1** [binary-person/womginx#82]
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

thats the message I got :I

**Comment by programmeruser2** [comment]
From the readme:
> Before you deploy to Heroku, read the following: Heroku decided that this repository violates the ToS, so directly clicking the button below if you're in the main repository will result in an error. Forked repositories may work, though this is not guaranteed. Regardless, I am NOT responsible if your Heroku account gets suspended because of deploying this application. Proceed at your own risk.

**Comment by binary-person** [comment]
see above
