### ISSUE TITLE
can you make a copy of this but a different link because my school blocked it

### ISSUE THREAD

**Issue by IncognitoCherry** [binary-person/womginx#86]

**Comment by IncognitoCherry** [comment]
can you make a copy of this with a different link because my school blocked this

**Comment by calebidklol** [comment]
what? just host your own... or go through the forks and find a running one.

**Comment by binary-person** [comment]
see above

**Comment by 3kh0** [comment]
@binary-person what is the best way to contact you? I have a few questions, if you wish I have discord: `3kh0_#1791`

**Comment by IncognitoCherry** [comment]
i added you (im cherryinheaven)

**Comment by binary-person** [comment]
email
