### ISSUE TITLE
Question about blocking (not school related)

### ISSUE THREAD

**Issue by zdc54** [binary-person/womginx#87]
My ISP blocked womginx.arph.org, which is fine. I understand that a school would block it, but why would Womginx get marked as a worm by an ISP?

**Comment by 3kh0** [comment]
because it is a proxy

**Comment by zdc54** [comment]
I know, but I want to prevent this in the future.

**Comment by binary-person** [comment]
web proxies are regarded as phishing because of its very nature of forwarding web content under a different domain, so it's expected this happens
