### ISSUE TITLE
question

### ISSUE THREAD

**Issue by noonoo5084** [binary-person/womginx#88]
would there be away to log the info the user types in? like logging their keystrokes on a certain website or smthn

**Comment by zdc54** [comment]
dude, don’t do this. this is not only highly illegal, but very immoral. and I can tell you that Simon (binary-person) is not appreciative of this. You can get in a crap-ton of trouble for this. I’m taking my time away from my stuff just to type this.

**Comment by noonoo5084** [comment]
sorry then ig
