### ISSUE TITLE
When I use it it says 403 forbidden

### ISSUE THREAD

**Issue by irhrhd** [binary-person/womginx#9]
Bug I think?

**Comment by binary-person** [comment]
womginx cookie hasn't been set on your device, causing the issue. Go to the main page of the proxy to set the cookie

**Comment by irhrhd** [comment]
How do I set the cookies

**Comment by binary-person** [comment]
go to https://womginx.synricha.org/ and type your url

**Comment by irhrhd** [comment]
I typed it now what?

**Comment by irhrhd** [comment]
I hit enter and it brought me to my heroku one

**Comment by binary-person** [comment]
go to your main page of your proxy and it sets the cookie automatically

**Comment by irhrhd** [comment]
Do I have to use the main proxy every time or can I use mine

**Comment by binary-person** [comment]
I'm sorry I did not make that clear. That was just an example. You need to go to the **root** page of your proxy and it sets the cookie automatically. like so: `https://yourherokuinstancehere.herokuapp.com/`

**Comment by irhrhd** [comment]
I use the root page and type the url I want to go to and it says 403

**Comment by binary-person** [comment]
post your heroku link here

**Comment by irhrhd** [comment]
I fixed it

**Comment by irhrhd** [comment]
Never mind
http://eggstastegood.herokuapp.com/
is my link

**Comment by binary-person** [comment]
I'm going to reopen the issue since it appears the 403 forbidden error more than occasionally pops up while using it.

The cookie gets removed from restarting the browser and sometimes gets removed by the proxied website. I'm going to implement a helpful redirect to correctly set the cookie so this error doesn't confuse anyone again.

**Comment by Dumbledore-web** [comment]
Is it possible to remove the cookie requirement? I have a website which I use privately to use this proxy and I had to set it up to redirect to the main proxy site before it goes to proxy.herokuapp.com/main/example.com (for example)

**Comment by NB714402** [comment]
To confused people with the 403, go to the page where you type the URL and do a cache reset (ctrl shift r on Chromebook)

**Comment by CactusHamster** [comment]
If you would like to remove the issue from the proxy completely, but risk allowing bots to use the proxy without cookies, you could comment out or remove lines 237-239 from `nginx.conf` in your own code and re-deploy to Heroku.

**Comment by neemanthnub** [comment]
> If you would like to remove the issue from the proxy completely, but risk allowing bots to use the proxy without cookies, you could comment out or remove lines 237-239 from `nginx.conf` in your own code and re-deploy to Heroku.

thanks

**Comment by binary-person** [comment]
alright. this is finally fixed. sorry for the wait everyone!
