### ISSUE TITLE
Assets failing to load

### ISSUE THREAD

**Issue by Craftzman7** [binary-person/womginx#90]
When I go to a website (for example discord.com) I am greeted with a mess of assets failing to load. (I was able to replicate on the public instance https://womginx.arph.org/ )

**Comment by binary-person** [comment]
does it say 429 rate limit exceeded?

**Comment by Craftzman7** [comment]
no

**Comment by binary-person** [comment]
it works for me. perhaps you meant the yellow warning messages saying the source map could not be found, in which case the official discord site is also like that. reopen this issue if it is otherwise

**Comment by Craftzman7** [comment]
Thats not the issue. Screenshot: https://cdn.femboy.host/AFcVPrGU
NOTE: It originally loads it for a few short seconds. Then does what shown above.

**Comment by binary-person** [comment]
oh that. react sites tend to not work well with womginx, given its simplified nature of only using nginx configs. thats an expected caveat of using this rewriting system

**Comment by Craftzman7** [comment]
Ok good to know
