### ISSUE TITLE
Discord not functioning

### ISSUE THREAD

**Issue by nyoosh** [binary-person/womginx#92]
Hello, I try to log onto Discord and nothing works. I've tried restarting the repl.it, I've tried refreshing, nothing works. Just says messages failed to load, no matter what i do. 
![Screenshot 2022-02-14 6 03 20 AM](https://user-images.githubusercontent.com/68951404/153861280-9be6fe75-e47f-427f-a9f3-716e999a7048.png)

**Comment by binary-person** [comment]
can you open chrome dev tools, go to console, then screenshot?

**Comment by WmeLuna** [comment]
also having this issue but only for repl... all api requests to discord result in a 429 error code
seems to be working fine on heroku as of rn

**Comment by binary-person** [comment]
that is because of discord rate limiting the proxy server's ip. in that case, using another womginx server will fix the problem
