### ISSUE TITLE
[Replit] The connection was reset. error

### ISSUE THREAD

**Issue by 3kh0** [binary-person/womginx#93]
When ever I use this on replit, it shows this error, I got a fresh new copy and the same thing.

![image](https://user-images.githubusercontent.com/58097612/154097683-bb4e5410-91ca-4809-b957-28582bae0999.png)

**Comment by Abnumality** [comment]
Are you doing this from a school chromebook?

**Comment by 3kh0** [comment]
yes, it is fixed now
