### ISSUE TITLE
Unable to sign in on discord

### ISSUE THREAD

**Issue by Erisfiregamer1** [binary-person/womginx#95]
Discord will not allow you to sign in on the proxy (Heroku, relay blocks Repl). It will act as if the login fields are empty.

**Comment by FoxNerdSaysMoo** [comment]
I can verify this error.
The console it just the same error spammed all over
![image](https://user-images.githubusercontent.com/65097669/154754019-cc4876ee-5453-4b17-bf4e-5f57d451feef.png)
![image](https://user-images.githubusercontent.com/65097669/154754062-defc48f5-89da-4c4c-896f-fb7711f32cbb.png)

**Comment by FoxNerdSaysMoo** [comment]
I believe that my problem was actually just something wierd with firefox, as womginx.arph.org still works for me with chrome

**Comment by binary-person** [comment]
i just downloaded firefox and it works on the womginx demo instance. can you paste in your proxy link so i can take a look?

**Comment by memedmusic** [comment]
I am also getting the same error Erisfiregamer1 is describing. Here is the error which is being shown in console 
![image](https://user-images.githubusercontent.com/55370047/154863784-5e9f7e98-b781-47e0-8b73-756c6eaca29b.png)

**Comment by binary-person** [comment]
is this happening in replit?

**Comment by memedmusic** [comment]
I'm getting that error with hosting locally on my windows 11 computer

**Comment by binary-person** [comment]
can you describe your hosting setup? i cannot replicate this in the official demo

**Comment by memedmusic** [comment]
> can you describe your hosting setup? i cannot replicate this in the official demo

My computer is just a windows 11 (latest) machine running docker and node (also latest versions). I installed it following the simple instillation guide, with the exception of changing the port number to 8000. I have used both v0.3.1 and 0.3.0 but still get the same error

**Comment by memedmusic** [comment]
update: qr code works, but logging in with credentials doesnt

**Comment by binary-person** [comment]
is this localhost with http? I haven't tested non-tls-enabled womginx

**Comment by memedmusic** [comment]
This is http with a connected domain, but same issue occurs on localhost

**Comment by binary-person** [comment]
try https and see if the issue persists

**Comment by memedmusic** [comment]
https seems to fix the issue

**Comment by Strange-Oddball** [comment]
@binary-person I'm not quite sure if you may have noticed but when you log into discord it brings you back to the login page. Is there something I can do to fix that?

**Comment by binary-person** [comment]
@Strange-Oddball see #98

**Comment by eris-webserv** [comment]
Looks like it's a http issue (https fixes it), BUT Captchas are broken. Maybe one-time, I'll test.

**Comment by eris-webserv** [comment]
Nope, it's more then one-time. I'll submit an issue.
